#!/usr/bin/env python
"""Generate controller exec anchors for a given simulator style.

Goal
- ref anchor stays fixed (e.g. Anchors_Original_256_centered.npy)
- exec anchor is generated by running PDMSimulator(tracker_style, post_style, post_params)
  on those anchors, then converting to ego-frame and downsampling to 8.

This is a lightweight, per-style generator intended for evaluation-time conditioning.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import random
import numpy as np

from nuplan.planning.simulation.trajectory.trajectory_sampling import TrajectorySampling

from navsim.planning.simulation.planner.pdm_planner.simulation.pdm_simulator import PDMSimulator
from nuplan.common.actor_state.ego_state import EgoState
from nuplan.common.actor_state.vehicle_parameters import get_pacifica_parameters
from navsim.common.dataclasses import Trajectory
from navsim.evaluate.pdm_score import (
    transform_trajectory,
    get_trajectory_as_array,
    global_traj_to_ego_all,
)


def _wrap_angle(a: np.ndarray) -> np.ndarray:
    return (a + np.pi) % (2 * np.pi) - np.pi


def _resample_traj_xyz(xy_yaw: np.ndarray, target_len: int) -> np.ndarray:
    """Resample a single trajectory [T,3] -> [target_len,3]."""
    t_old = np.arange(xy_yaw.shape[0], dtype=float)
    t_new = np.linspace(0, xy_yaw.shape[0] - 1, target_len, dtype=float)

    x_old, y_old, yaw_old = xy_yaw[:, 0], xy_yaw[:, 1], xy_yaw[:, 2]
    x_new = np.interp(t_new, t_old, x_old)
    y_new = np.interp(t_new, t_old, y_old)

    yaw_unwrap = np.unwrap(yaw_old)
    yaw_new = np.interp(t_new, t_old, yaw_unwrap)
    yaw_new = _wrap_angle(yaw_new)

    return np.stack([x_new, y_new, yaw_new], axis=-1)


def resample_anchors_to_41(anchors: np.ndarray) -> np.ndarray:
    """Resample anchors [256,T,>=3] to [256,41,3]."""
    b, t, d = anchors.shape
    assert b == 256, f"Expected 256 anchors, got {b}"
    assert d >= 3, "Anchors last dim must be >=3 (x,y,yaw)"

    out = np.zeros((b, 41, 3), dtype=np.float32)
    for i in range(b):
        out[i] = _resample_traj_xyz(anchors[i, :, :3], 41)
    return out


def downsample_to_8(traj: np.ndarray) -> np.ndarray:
    """traj: [N, T, 3] -> [N, 8, 3]"""
    t = traj.shape[1]
    idx = np.linspace(0, t - 1, 8, dtype=int)
    return traj[:, idx, :3]


def ego_from_anchor_pair(p0: np.ndarray, p1: np.ndarray, dt: float = 0.1) -> EgoState:
    """Construct EgoState using first two anchor poses to estimate initial velocity/yaw_rate."""
    x0, y0, yaw0 = float(p0[0]), float(p0[1]), float(p0[2])
    x1, y1, yaw1 = float(p1[0]), float(p1[1]), float(p1[2])
    dx, dy, dyaw = (x1 - x0), (y1 - y0), (yaw1 - yaw0)

    vx_ego, vy_ego = dx / dt, dy / dt
    cos0, sin0 = np.cos(yaw0), np.sin(yaw0)
    vx = vx_ego * cos0 - vy_ego * sin0
    vy = vx_ego * sin0 + vy_ego * cos0
    yaw_rate = dyaw / dt

    vec9 = [0, x0, y0, yaw0, vx, vy, 0.0, 0.0, yaw_rate]
    return EgoState.deserialize(vec9, get_pacifica_parameters())


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--ref", required=True, type=str, help="ref anchor .npy")
    p.add_argument("--out", required=True, type=str, help="output exec anchor .npy")

    p.add_argument("--tracker-style", default="default", type=str)
    p.add_argument("--post-style", default="none", type=str)

    # How post transform is applied inside PDMSimulator.
    # online: applied at each rollout step (affects x/y)
    # offline: applied once after rollout (legacy)
    # auto: online only when params are non-default
    p.add_argument("--apply-mode", default="online", type=str, choices=["online", "offline", "auto"])

    p.add_argument("--heading-scale", default=1.0, type=float)
    p.add_argument("--heading-bias", default=0.0, type=float)
    p.add_argument("--speed-scale", default=1.0, type=float)
    p.add_argument("--speed-bias", default=0.0, type=float)
    p.add_argument("--noise-std", default=0.0, type=float)

    p.add_argument("--seed", default=42, type=int)
    p.add_argument("--force", action="store_true", help="overwrite if exists")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    random.seed(args.seed)
    np.random.seed(args.seed)

    ref_path = Path(args.ref)
    out_path = Path(args.out)

    if out_path.exists() and not args.force:
        print(f"[INFO] exists, skip: {out_path}")
        return

    ref = np.load(str(ref_path))
    if ref.ndim != 3:
        raise ValueError(f"ref anchor must be 3D array, got shape={ref.shape}")

    # normalize to [256,41,3]
    if ref.shape[1] != 41:
        ref_41 = resample_anchors_to_41(ref.astype(np.float32))
    else:
        ref_41 = ref[:, :, :3].astype(np.float32)

    proposal_sampling = TrajectorySampling(time_horizon=4.0, interval_length=0.1)
    initial_state = ego_from_anchor_pair(ref_41[0, 0, :3], ref_41[0, 1, :3], dt=0.1)

    post_params = {
        "style": args.post_style,
        "apply_mode": args.apply_mode,
        "heading_scale": float(args.heading_scale),
        "heading_bias": float(args.heading_bias),
        "speed_scale": float(args.speed_scale),
        "speed_bias": float(args.speed_bias),
        "noise_std": float(args.noise_std),
    }

    simulator = PDMSimulator(
        proposal_sampling=proposal_sampling,
        tracker_style=args.tracker_style,
        post_style=args.post_style,
        post_params=post_params,
    )

    all_states = []
    for a_idx in range(ref_41.shape[0]):
        rel_poses = ref_41[a_idx, 1:, :3]  # drop t=0, use future 40 steps
        traj = Trajectory(poses=rel_poses, trajectory_sampling=proposal_sampling)
        global_traj = transform_trajectory(traj, initial_state)
        traj_states = get_trajectory_as_array(global_traj, proposal_sampling, initial_state.time_point)
        all_states.append(traj_states)

    proposal_states = np.stack(all_states, axis=0)
    exec_global = simulator.simulate_proposals(proposal_states, initial_state)
    exec_ego = global_traj_to_ego_all(exec_global, initial_state)

    exec_8 = downsample_to_8(exec_ego.astype(np.float32))  # [256,8,3]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.save(str(out_path), exec_8)
    print(f"[OK] saved exec anchor: {out_path} shape={exec_8.shape}")


if __name__ == "__main__":
    main()
