#!/usr/bin/env python3
"""Fuse cam6 mosaic (left) + BEV focused plot (right) into one image.

Expected existing outputs:
- cam6 mosaic: <cam6_root>/<token>/<token>_<YYYYMMDD>_<HHMMSS>_cam6.png
  (generated by tool/smalltool/visualize_token_cameras_6view.py)
- BEV focused plot: <bev_root>/<token>/<token>_<YYYYMMDD>_<HHMMSS>.png
  (generated by tool/smalltool/visualize_token_compare.py)

This script:
- For each token, finds the best-matching pair by timestamp (closest time).
- Resizes BEV image to match cam6 image height (keeps aspect ratio).
- Concatenates horizontally: [cam6 | bev]
- Writes fused image into <out_root>/<token>/ (PNG/PDF)

Notes:
- If cam6 image is missing for a token, the script will try to auto-generate it by
  invoking visualize_token_cameras_6view.py (needs OPENSCENE_DATA_ROOT etc.).
- If BEV image is missing, the script fails for that token (since BEV generation
  requires ckpt args not provided here).
"""

from __future__ import annotations

import argparse
import base64
import datetime
import io
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional


DEFAULT_CAM6_ROOT = Path("/home/zhaodanqi/clone/WoTE/WorldCAP_pic/6camScenarios")
DEFAULT_BEV_ROOT = Path("/home/zhaodanqi/clone/WoTE/WorldCAP_pic/scenario/scenarios_collisonatfault")


_TS_RE = re.compile(r"^(?P<token>[0-9a-f]+)_(?P<date>\d{8})_(?P<time>\d{6})(?P<rest>.*)$")


@dataclass(frozen=True)
class _ImgCandidate:
    path: Path
    ts: Optional[datetime.datetime]


def _resolve_token_dir(root: Path, token: str) -> Optional[Path]:
    """Resolve a token directory under root.

    Supports folder names that start with token, e.g. '<token>--good'.
    Returns None if no matching directory exists.
    """

    try:
        if not root.exists():
            return None
        matches = [p for p in root.iterdir() if p.is_dir() and p.name.startswith(token)]
        if not matches:
            return None
        exact = next((p for p in matches if p.name == token), None)
        if exact is not None:
            return exact
        best = max(matches, key=lambda p: (p.stat().st_mtime, -len(p.name)))
        if len(matches) > 1:
            names = ", ".join(sorted([p.name for p in matches]))
            print(
                f"[WARN] multiple dirs start with token '{token}' under {root}: {names}; using '{best.name}'",
                file=sys.stderr,
            )
        return best
    except Exception:
        return None


def _parse_ts_from_stem(token: str, stem: str) -> Optional[datetime.datetime]:
    m = _TS_RE.match(stem)
    if not m:
        return None
    if m.group("token") != token:
        return None
    try:
        return datetime.datetime.strptime(m.group("date") + m.group("time"), "%Y%m%d%H%M%S")
    except Exception:
        return None


def _list_cam6_candidates(cam6_root: Path, token: str) -> list[_ImgCandidate]:
    token_dir = _resolve_token_dir(cam6_root, token)
    if token_dir is None or not token_dir.exists():
        return []

    out: list[_ImgCandidate] = []
    for p in sorted(token_dir.glob(f"{token}_*_cam6.png")):
        ts = _parse_ts_from_stem(token, p.stem)
        out.append(_ImgCandidate(path=p, ts=ts))
    return out


def _is_bev_focus_png(token: str, p: Path) -> bool:
    if p.suffix.lower() != ".png":
        return False
    if not p.name.startswith(token + "_"):
        return False
    # Exclude non-focus outputs
    s = p.stem
    if s.endswith("_baseline") or s.endswith("_worldcap"):
        return False
    if s.endswith("_cam6") or s.endswith("_cam6_bev"):
        return False
    if s.endswith("_6view_bev"):
        return False
    return True


def _list_bev_candidates(bev_root: Path, token: str) -> list[_ImgCandidate]:
    token_dir = _resolve_token_dir(bev_root, token)
    if token_dir is None or not token_dir.exists():
        return []

    out: list[_ImgCandidate] = []
    for p in sorted(token_dir.glob(f"{token}_*.png")):
        if not _is_bev_focus_png(token, p):
            continue
        ts = _parse_ts_from_stem(token, p.stem)
        out.append(_ImgCandidate(path=p, ts=ts))
    return out


def _pick_latest_by_mtime(cands: list[_ImgCandidate]) -> Optional[_ImgCandidate]:
    if not cands:
        return None
    return max(cands, key=lambda c: c.path.stat().st_mtime)


def _pick_best_pair(
    cam6_cands: list[_ImgCandidate],
    bev_cands: list[_ImgCandidate],
) -> tuple[Optional[_ImgCandidate], Optional[_ImgCandidate]]:
    if not cam6_cands or not bev_cands:
        return (None, None)

    # If both sides have timestamps, match the closest.
    cam6_ts = [c for c in cam6_cands if c.ts is not None]
    bev_ts = [c for c in bev_cands if c.ts is not None]
    if cam6_ts and bev_ts:
        best: tuple[float, _ImgCandidate, _ImgCandidate] | None = None
        for b in bev_ts:
            for c in cam6_ts:
                dt = abs((b.ts - c.ts).total_seconds())
                if best is None or dt < best[0]:
                    best = (dt, c, b)
        assert best is not None
        return (best[1], best[2])

    # Fallback: pick newest files.
    return (_pick_latest_by_mtime(cam6_cands), _pick_latest_by_mtime(bev_cands))


def _ensure_cam6_exists(
    *,
    token: str,
    cam6_root: Path,
    split: str,
    metric_cache_path: Optional[Path],
    navsim_log_path: Optional[Path],
    sensor_blobs_path: Optional[Path],
) -> None:
    """Generate cam6 mosaic if missing."""

    if _list_cam6_candidates(cam6_root, token):
        return

    repo_root = Path(__file__).resolve().parents[2]
    cam6_script = repo_root / "tool" / "smalltool" / "visualize_token_cameras_6view.py"
    if not cam6_script.exists():
        raise RuntimeError(f"cam6 script not found: {cam6_script}")

    cmd: list[str] = [sys.executable, str(cam6_script), "--token", token, "--split", split, "--out-dir", str(cam6_root)]
    if metric_cache_path is not None:
        cmd += ["--metric-cache-path", str(metric_cache_path)]
    if navsim_log_path is not None:
        cmd += ["--navsim-log-path", str(navsim_log_path)]
    if sensor_blobs_path is not None:
        cmd += ["--sensor-blobs-path", str(sensor_blobs_path)]

    subprocess.run(cmd, check=True)


def _fuse_one(
    *,
    token: str,
    cam6_path: Path,
    bev_path: Path,
    out_path: Path,
    gap_px: int,
) -> None:
    from PIL import Image

    cam6 = Image.open(cam6_path)
    bev = Image.open(bev_path)

    if cam6.mode != "RGB":
        cam6 = cam6.convert("RGB")
    if bev.mode != "RGB":
        bev = bev.convert("RGB")

    # Resize BEV by cam6 height
    target_h = int(cam6.height)
    if target_h <= 0:
        raise RuntimeError("cam6 image has invalid height")

    if bev.height != target_h:
        target_w = max(1, int(round(bev.width * (target_h / float(bev.height)))))
        bev = bev.resize((target_w, target_h), resample=Image.BILINEAR)

    gap_px = int(max(0, gap_px))
    canvas = Image.new("RGB", (cam6.width + gap_px + bev.width, cam6.height))
    canvas.paste(cam6, (0, 0))
    canvas.paste(bev, (cam6.width + gap_px, 0))

    # Only create the directory when missing.
    if not out_path.parent.exists():
        out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def _save_as_svg(rgb_img, out_svg: Path) -> None:
    """Save a PIL RGB image into an SVG container (PNG base64 embedded)."""

    if not out_svg.parent.exists():
        out_svg.parent.mkdir(parents=True, exist_ok=True)

    w, h = int(rgb_img.width), int(rgb_img.height)
    buf = io.BytesIO()
    rgb_img.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")

    # Use href (SVG2) with xlink fallback for compatibility.
    svg = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'width="{w}" height="{h}" viewBox="0 0 {w} {h}">\n'
        f'  <image width="{w}" height="{h}" '
        f'href="data:image/png;base64,{b64}" '
        f'xlink:href="data:image/png;base64,{b64}"/>\n'
        '</svg>\n'
    )
    out_svg.write_text(svg, encoding="utf-8")


def _read_token_file(p: Path) -> list[str]:
    tokens: list[str] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        tokens.append(s)
    return tokens


def _unique_in_order(xs: Iterable[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for x in xs:
        s = (x or "").strip()
        if not s or s in seen:
            continue
        seen.add(s)
        out.append(s)
    return out


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()

    p.add_argument("--token", default=None, help="single token")
    p.add_argument("--tokens", nargs="+", default=None, help="multiple tokens")
    p.add_argument("--token-file", default=None, help="text file with tokens (one per line)")

    p.add_argument(
        "--cam6-root",
        default=str(DEFAULT_CAM6_ROOT),
        help="cam6 output root dir (contains <token>/<token>_*_cam6.png)",
    )
    p.add_argument(
        "--bev-root",
        default=str(DEFAULT_BEV_ROOT),
        help="BEV focus output root dir (contains <token>/<token>_*.png)",
    )
    p.add_argument(
        "--out-root",
        default=str(DEFAULT_BEV_ROOT),
        help="where to write fused outputs (will create <token>/)",
    )

    p.add_argument(
        "--split",
        default="val",
        help="dataset split used when auto-generating cam6 (default: val)",
    )
    p.add_argument(
        "--metric-cache-path",
        default="",
        help="optional metric_cache path passed to cam6 generator (helps auto-detect split/log_name)",
    )
    p.add_argument(
        "--navsim-log-path",
        default="",
        help="optional navsim_log_path passed to cam6 generator",
    )
    p.add_argument(
        "--sensor-blobs-path",
        default="",
        help="optional sensor_blobs_path passed to cam6 generator",
    )

    p.add_argument("--gap", type=int, default=0, help="horizontal gap (pixels) between cam6 and BEV")
    p.add_argument("--overwrite", action="store_true", help="overwrite existing fused image")
    p.add_argument(
        "--format",
        default="both",
        choices=["png", "svg", "both"],
        help="output format for fused image (default: both)",
    )

    return p.parse_args()


def main() -> int:
    args = _parse_args()

    tokens_raw: list[str] = []
    if args.token:
        tokens_raw.append(str(args.token))
    if args.tokens:
        tokens_raw.extend([str(t) for t in args.tokens])
    if args.token_file:
        token_file = Path(args.token_file).expanduser().resolve()
        if not token_file.exists():
            print(f"ERROR: --token-file not found: {token_file}", file=sys.stderr)
            return 2
        tokens_raw.extend(_read_token_file(token_file))

    tokens = _unique_in_order(tokens_raw)
    if not tokens:
        print("ERROR: no tokens provided", file=sys.stderr)
        return 2

    cam6_root = Path(args.cam6_root).expanduser().resolve()
    bev_root = Path(args.bev_root).expanduser().resolve()
    out_root = Path(args.out_root).expanduser().resolve()

    metric_cache_path = Path(args.metric_cache_path).expanduser().resolve() if args.metric_cache_path else None
    navsim_log_path = Path(args.navsim_log_path).expanduser().resolve() if args.navsim_log_path else None
    sensor_blobs_path = Path(args.sensor_blobs_path).expanduser().resolve() if args.sensor_blobs_path else None

    failures = 0
    for token in tokens:
        try:
            # Ensure cam6 exists (auto-generate if needed)
            _ensure_cam6_exists(
                token=token,
                cam6_root=cam6_root,
                split=str(args.split),
                metric_cache_path=metric_cache_path,
                navsim_log_path=navsim_log_path,
                sensor_blobs_path=sensor_blobs_path,
            )

            cam6_cands = _list_cam6_candidates(cam6_root, token)
            bev_cands = _list_bev_candidates(bev_root, token)

            if not bev_cands:
                raise RuntimeError(f"BEV focus image not found under: {bev_root} (dir name startswith '{token}')")

            cam6_best, bev_best = _pick_best_pair(cam6_cands, bev_cands)
            if cam6_best is None:
                raise RuntimeError(f"cam6 image not found under: {cam6_root} (dir name startswith '{token}')")
            if bev_best is None:
                raise RuntimeError(f"BEV focus image not found under: {bev_root} (dir name startswith '{token}')")

            # Name fused image using BEV stem (keeps the main timestamp consistent)
            out_dir = _resolve_token_dir(out_root, token) or (out_root / token)

            from PIL import Image

            cam6_img = Image.open(cam6_best.path).convert("RGB")
            bev_img = Image.open(bev_best.path).convert("RGB")

            target_h = int(cam6_img.height)
            if target_h <= 0:
                raise RuntimeError("cam6 image has invalid height")
            if bev_img.height != target_h:
                target_w = max(1, int(round(bev_img.width * (target_h / float(bev_img.height)))))
                bev_img = bev_img.resize((target_w, target_h), resample=Image.BILINEAR)

            gap_px = int(max(0, int(args.gap)))
            fused = Image.new("RGB", (cam6_img.width + gap_px + bev_img.width, cam6_img.height))
            fused.paste(cam6_img, (0, 0))
            fused.paste(bev_img, (cam6_img.width + gap_px, 0))

            wrote_any = False
            if args.format in {"png", "both"}:
                out_png = out_dir / f"{bev_best.path.stem}_cam6_bev.png"
                if out_png.exists() and not bool(args.overwrite):
                    print(f"[SKIP] exists: {out_png}")
                else:
                    if not out_png.parent.exists():
                        out_png.parent.mkdir(parents=True, exist_ok=True)
                    fused.save(out_png)
                    wrote_any = True

            if args.format in {"svg", "both"}:
                out_svg = out_dir / f"{bev_best.path.stem}_cam6_bev.svg"
                if out_svg.exists() and not bool(args.overwrite):
                    print(f"[SKIP] exists: {out_svg}")
                else:
                    _save_as_svg(fused, out_svg)
                    wrote_any = True

            if wrote_any:
                print("=== fused done ===")
                print(f"token: {token}")
                print(f"cam6:  {cam6_best.path}")
                print(f"bev:   {bev_best.path}")
                print(f"out:   {out_dir}")
        except subprocess.CalledProcessError as e:
            failures += 1
            print(f"[ERR] token failed: {token} (cam6 generator failed: {e})", file=sys.stderr)
        except Exception as e:
            failures += 1
            print(f"[ERR] token failed: {token} ({e})", file=sys.stderr)

    return 0 if failures == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
