#!/usr/bin/env bash
set -euo pipefail

# WoTE training script (controller-conditioned world model) using controller bundle train/val split.
#
# Key behavior:
# - Training-time controller style is randomly sampled from bundle *train* split only.
#   (bundle generated by ControllerExp/scripts/genTest.py)
# - Validation/evaluation of *held-out controller styles* should be done by running eval scripts
#   with CTRL_STYLE_IDX set to an index from ControllerExp/generated/val_styles.txt.
#   (Those eval scripts will also force the simulator to use the same style.)
#
# Usage:
#   CUDA_VISIBLE_DEVICES=0,1 \
#   NAVSIM_EXP_ROOT=/path/to/exp_root \
#   bash tool/training/0224train_wote_ctrlbundle_split_train_attn.sh

# Recommended for this setting (freeze policy; train WM + reward heads only)
export WOTE_TRAIN_PROFILE=${WOTE_TRAIN_PROFILE:-wm_reward_only}

ROOT=${ROOT:-/home/zhaodanqi/clone/WoTE}

# -----------------------------
# Controller bundle split control
# -----------------------------
# Restrict training-time random style sampling to the bundle's train split.
export WOTE_CTRL_STYLE_SPLIT=${WOTE_CTRL_STYLE_SPLIT:-train}
# If this is set, sampling is disabled and training becomes single-style.
if [[ -n "${WOTE_CTRL_STYLE_IDX:-}" ]]; then
  echo "[WARN] WOTE_CTRL_STYLE_IDX is set (${WOTE_CTRL_STYLE_IDX}); training will be FIXED style (no sampling)." >&2
  echo "[WARN] Unset it to enable train-split sampling: unset WOTE_CTRL_STYLE_IDX" >&2
fi

# Prefer current env python. Override with: export PYTHON=/abs/path/to/python
if [[ -n "${PYTHON:-}" ]]; then
  :
elif command -v python >/dev/null 2>&1; then
  PYTHON=$(command -v python)
elif command -v python3 >/dev/null 2>&1; then
  PYTHON=$(command -v python3)
else
  echo "[ERR] Cannot find python. Activate your conda/venv first or export PYTHON=/abs/path/to/python" >&2
  exit 1
fi

echo "[INFO] Using PYTHON=${PYTHON}"
"${PYTHON}" -c "import sys; print('[INFO] python:', sys.executable); print('[INFO] version:', sys.version.replace('\\n',' '))" || true

# GPUs
# Manual control options:
#   GPU_IDS=0,1,2,3        -> sets CUDA_VISIBLE_DEVICES explicitly
#   GPU_NUM=4              -> forces trainer.devices=4
# You can also set DEVICES directly (takes priority over auto-derivation).
GPU_IDS=${GPU_IDS:-"0,1,2,3"}
GPU_NUM=${GPU_NUM:-""}

if [[ -n "${GPU_IDS}" ]]; then
  export CUDA_VISIBLE_DEVICES="${GPU_IDS}"
fi

if [[ -z "${CUDA_VISIBLE_DEVICES:-}" ]]; then
  export CUDA_VISIBLE_DEVICES="0"
fi

if [[ -n "${GPU_NUM}" && -z "${DEVICES:-}" ]]; then
  DEVICES="${GPU_NUM}"
fi

echo "[INFO] CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"

# Python import paths
export PYTHONPATH="${ROOT}/navsim:${PYTHONPATH:-}"
export PYTHONPATH="${ROOT}/nuplan-devkit:${PYTHONPATH:-}"

# -----------------------------
# Inputs / paths
# -----------------------------
PLANNER_ANCHORS=${PLANNER_ANCHORS:-"${ROOT}/extra_data/planning_vb/trajectory_anchors_256.npy"}

# Controller bank (ref/exec). Use .npz exec bundle to train for multi-style generalization.
CTRL_REF=${CTRL_REF:-"${ROOT}/ControllerExp/Anchors_Original_256_centered.npy"}
CTRL_EXEC=${CTRL_EXEC:-"${ROOT}/ControllerExp/generated/controller_styles.npz"}

# NAVSIM_EXP_ROOT is used by hydra config to construct output_dir.
NAVSIM_EXP_ROOT=${NAVSIM_EXP_ROOT:-"${ROOT}"}
export NAVSIM_EXP_ROOT

CACHE_PATH=${CACHE_PATH:-"${NAVSIM_EXP_ROOT}/training_cache_allWoteTarget_0114"}

# -----------------------------
# Training hyperparams
# -----------------------------
BATCH_SIZE=${WOTE_BATCH_SIZE:-16}
MAX_EPOCHS=${WOTE_MAX_EPOCHS:-40}
LR=${WOTE_LR:-"1e-4"}
MIN_LR=${WOTE_MIN_LR:-"1e-6"}
WARMUP_EPOCHS=${WOTE_WARMUP_EPOCHS:-3}

# Devices for Lightning Trainer.
if [[ -z "${DEVICES:-}" ]]; then
  _cvis="${CUDA_VISIBLE_DEVICES// /}"
  if [[ "${_cvis}" =~ ^[0-9]+-[0-9]+$ ]]; then
    _start="${_cvis%-*}"
    _end="${_cvis#*-}"
    DEVICES=$(( _end - _start + 1 ))
  else
    IFS=',' read -ra _gpu_ids <<<"${_cvis}"
    DEVICES=${#_gpu_ids[@]}
  fi
fi

echo "[INFO] trainer.devices=${DEVICES}"

# -----------------------------
# Controller → WM knobs
# -----------------------------
CTRL_FEATURE_MODE=${CTRL_FEATURE_MODE:-full}        # full | lateral_only
CTRL_POOLING=${CTRL_POOLING:-attn}                 # attn | mean
WM_INJECT_TARGET=${WM_INJECT_TARGET:-all}          # all | ego

# World-model fusion modes to run in sequence (comma-separated):
#   RUN_FUSIONS=attn,film03   -> train attn first, then film03
# You can also run a single one: RUN_FUSIONS=attn
RUN_FUSIONS=${RUN_FUSIONS:-"attn,film03"}

# Strength is only used for fusion=film* and fusion=add (legacy).
WM_STRENGTH_ATTN=${WM_STRENGTH_ATTN:-"0.0"}
WM_STRENGTH_FILM=${WM_STRENGTH_FILM:-"0.3"}
WM_STRENGTH_ADD=${WM_STRENGTH_ADD:-"0.3"}

# Loss weights
IM_LOSS_W=${IM_LOSS_W:-1.0}
METRIC_LOSS_W=${METRIC_LOSS_W:-1.0}

# Experiment naming
EXP_BASE=${EXP_BASE:-"WoTE/cap_controller_bundle_split"}
EXP_TAG_BASE=${EXP_TAG_BASE:-"ctrlbundle_trainSplit"}
RUN_TS=${RUN_TS:-"$(date +%Y%m%d_%H%M%S)"}
EXP_RUN_ID=${EXP_RUN_ID:-"${RUN_TS}"}

preflight_one() {
  local fusion="$1"; shift
  local strength="$1"; shift

  echo "[INFO] Preflight: fusion=${fusion} strength=${strength} pooling=${CTRL_POOLING}"
  "${PYTHON}" - <<PY
from navsim.agents.WoTE.configs.default import WoTEConfig
from navsim.agents.WoTE.WoTE_model import WoTEModel
import os

cfg = WoTEConfig()
cfg.cluster_file_path = r"""${PLANNER_ANCHORS}"""
cfg.controller_ref_traj_path = r"""${CTRL_REF}"""
cfg.controller_exec_traj_path = r"""${CTRL_EXEC}"""
cfg.controller_feature_mode = r"""${CTRL_FEATURE_MODE}"""
cfg.controller_style_pooling = r"""${CTRL_POOLING}"""
cfg.controller_world_model_fusion = r"""${fusion}"""
cfg.controller_world_model_strength = float(r"""${strength}""")

m = WoTEModel(cfg)
need = ['ctrl_proj', 'ctrl_token_ln', 'controller_encoder']
pooling = str(r"""${CTRL_POOLING}""" or 'attn').lower()
fusion_s = str(r"""${fusion}""" or 'attn').lower()
if pooling == 'attn':
  need += ['ctrl_style_attn']

if fusion_s in {'attn', 'attention', 'cross_attn', 'cross_attention'}:
  need += ['ctrl_fuse_attn', 'ctrl_bank_proj', 'ctrl_bank_ln']
elif fusion_s.startswith('film'):
  need += ['ctrl_wm_film_scale', 'ctrl_wm_film_shift', 'ctrl_wm_film_ln']

missing = [k for k in need if not hasattr(m, k)]
if missing:
  raise RuntimeError('Preflight failed, missing attrs: ' + ','.join(missing))

ctrl_exec = r"""${CTRL_EXEC}"""
if ctrl_exec and (not os.path.isfile(ctrl_exec)):
  raise RuntimeError('CTRL_EXEC does not exist on disk: ' + ctrl_exec)

print('[INFO] Preflight OK:', 'fusion='+fusion_s, 'strength='+str(cfg.controller_world_model_strength))
print('[INFO] WOTE_CTRL_STYLE_SPLIT =', os.environ.get('WOTE_CTRL_STYLE_SPLIT', ''))
print('[INFO] WOTE_CTRL_STYLE_IDX   =', os.environ.get('WOTE_CTRL_STYLE_IDX', ''))
PY
}

run_one() {
  local exp_suffix="$1"; shift
  local fusion="$1"; shift
  local strength="$1"; shift

  echo "============================================================"
  echo "[TRAIN] ${EXP_BASE}/${exp_suffix}"
  echo "  anchors      = ${PLANNER_ANCHORS}"
  echo "  ctrl_ref     = ${CTRL_REF}"
  echo "  ctrl_exec    = ${CTRL_EXEC}"
  echo "  cache_path   = ${CACHE_PATH}"
  echo "  devices      = ${DEVICES} (visible: ${CUDA_VISIBLE_DEVICES})"
  echo "  ctrl_split   = ${WOTE_CTRL_STYLE_SPLIT}"
  echo "  ctrl->wm     = enable=true fusion=${fusion} strength=${strength} target=${WM_INJECT_TARGET}"
  echo "  ctrl_pooling = ${CTRL_POOLING}"
  echo "  feature_mode = ${CTRL_FEATURE_MODE}"
  echo "  im_w/metric_w= ${IM_LOSS_W}/${METRIC_LOSS_W}"
  echo "  WOTE_TRAIN_PROFILE=${WOTE_TRAIN_PROFILE}"
  echo "============================================================"

  "${PYTHON}" ./navsim/planning/script/run_training.py \
    agent=WoTE_agent \
    agent.config._target_=navsim.agents.WoTE.configs.default.WoTEConfig \
    ++agent.config.cluster_file_path="${PLANNER_ANCHORS}" \
    ++agent.config.controller_ref_traj_path="${CTRL_REF}" \
    ++agent.config.controller_exec_traj_path="${CTRL_EXEC}" \
    use_cache_without_dataset=true \
    cache_path="${CACHE_PATH}" \
    dataloader.params.batch_size=${BATCH_SIZE} \
    trainer.params.max_epochs=${MAX_EPOCHS} \
    +trainer.params.devices=${DEVICES} \
    split=trainval \
    experiment_name="${EXP_BASE}/${exp_suffix}" \
    scene_filter=navtrain \
    agent.lr=${LR} \
    agent.config.min_lr=${MIN_LR} \
    agent.config.warmup_epochs=${WARMUP_EPOCHS} \
    ++agent.config.controller_feature_mode=${CTRL_FEATURE_MODE} \
    ++agent.config.controller_style_pooling=${CTRL_POOLING} \
    ++agent.config.controller_condition_on_world_model=true \
    ++agent.config.controller_world_model_fusion=${fusion} \
    ++agent.config.controller_world_model_strength=${strength} \
    ++agent.config.controller_world_model_inject_target=${WM_INJECT_TARGET} \
    ++agent.config.use_agent_loss=false \
    ++agent.config.use_map_loss=true \
    ++agent.config.bev_semantic_weight=0.5 \
    ++agent.config.fut_bev_semantic_weight=1.0 \
    ++agent.config.traj_offset_loss_weight=0.2 \
    ++agent.config.offset_im_reward_weight=0.1 \
    ++agent.config.im_loss_weight=${IM_LOSS_W} \
    ++agent.config.metric_loss_weight=${METRIC_LOSS_W} \
    "$@"
}

IFS=',' read -ra _fusions <<<"${RUN_FUSIONS}"
if [[ ${#_fusions[@]} -eq 0 ]]; then
  echo "[ERR] RUN_FUSIONS is empty" >&2
  exit 2
fi

for _fusion in "${_fusions[@]}"; do
  _fusion="${_fusion// /}"
  if [[ -z "${_fusion}" ]]; then
    continue
  fi

  _strength="${WM_STRENGTH_ATTN}"
  if [[ "${_fusion}" == add* ]]; then
    _strength="${WM_STRENGTH_ADD}"
  elif [[ "${_fusion}" == film* ]]; then
    _strength="${WM_STRENGTH_FILM}"
  fi

  preflight_one "${_fusion}" "${_strength}"
  run_one "${EXP_TAG_BASE}_${_fusion}_${EXP_RUN_ID}" "${_fusion}" "${_strength}"
done

echo "[DONE] Training finished (${RUN_FUSIONS})."

echo ""
echo "[NEXT] Held-out controller-style eval (manual):"
echo "  1) pick an index from: ${ROOT}/ControllerExp/generated/val_styles.txt"
echo "  2) run eval with matched simulator+embedding style, e.g.:"
echo "     CTRL_STYLE_IDX=<IDX> bash tool/evaluate/evaluate_ckpt_attn_s01_s10_onlinepost.sh"
